package go_apario_identifier

const VERSION = `0.0.1`

// TO GET YOUR RUNNING INSTANCE OF APARIO IDENTIFIER IN THE README.md JUST
// EMAIL DIRECTOR@PROJECTAPARIO.COM TO TELL US WHAT DOMAIN NAME TO ADD.

// IF YOU WANT TO PLACE A SPONSORED MESSAGE ON THE README OF THIS PROJECT.
// EACH CURRENCY EXCHANGE IS BASED ON TOKEN VALUE VERSUS SERVICE PROVIDED.
// SOME CURRENCIES WILL BE MORE FAVORABLE THAN OTHERS. OFFER SUBJECT TO CHANGE.
// IN ORDER TO GET YOUR CHARACTERS OR IMAGE ADDED, YOU MUST SUBMIT A NEW
// PULL REQUEST WITH YOUR CHARACTERS AND/OR IMAGE. ALL IMAGES MUST BE PLACED
// INSIDE THE FOLDER CALLED IMAGES AND MUST BE REFERENCED WITH LOCAL
// MARKDOWN ONLY. YOU CANNOT USE A LINKED IMAGE SOURCED FROM ANOTHER SITE.
// IN THE DESCRIPTION OF THE PULL REQUEST PLACE THE TRANSACTION ID AND THE
// LEVEL THAT YOU ARE REDEEMING WITH THIS TRANSACTION.
// TIMER FOR TIME BASED PRODUCTS DOES NOT BEGIN UNTIL 24 HOURS AFTER THE
// PULL REQUEST IS MERGED.

// ADVERTISING CHARACTERS SUBJECT TO PROJECT APARIO'S COMMUNITY STANDARDS
// ADVERTISING CHARACTERS SUBJECT TO GITHUB'S COMMUNITY STANDARDS
// ADVERTISING IMAGES SUBJECT TO PROJECT APARIO'S COMMUNITY STANDARDS
// ADVERTISING IMAGES SUBJECT TO GITHUB'S COMMUNITY STANDARDS
// ADVERTISING CHARACTERS MUST NOT CONTAIN TRADEMARKS OR COPYRIGHTS OF WHICH YOU DO NOT HAVE PERMISSION TO USE
// ADVERTISING IMAGES MUST NOT CONTAIN TRADEMARKS OR COPYRIGHTS OF WHICH YOU DO NOT HAVE PERMISSION TO USE
// ADVERTISING OPPORTUNITIES EXIST SOLELY AT THE VOLUNTARY DISCRETION OF PROJECT APARIO

// AN AD IS:
// CHARACTERS OF ALL LANGUAGES PERMITTED - MUST INCLUDE ENGLISH TRANSACTION AS MINIMUM SUBMISSION
// MUST BE SELLING A PRODUCT OR SERVICE
// MUST NOT BE CONNECTED WITH A POLITICAL CAMPAIGN OF A REPRESENTATIVE FOR PUBLIC OFFICE
// MUST NOT BE CONNECTED WITH ILLEGAL OR UNETHICAL PRACTICES
// MUST INCLUDE A LINK TO A VALID WEBSITE
// MUST VERIFY OWNERSHIP OF THE WEBSITE (IN A TEXT FILE UPLOAD THE TRANSACTION IDENTIFIER TO ~/.well-known/apario-verification OR CNAME apario_identifier OR email from <webmaster|administrator|admin>@<the domain of the website>)
// MUST COMMIT TO SERVING WEBSITE FOR FULL DURATION OF THE CAMPAIGN

// TERMS INCLUDE:
// 1. NO REFUNDS OF ANY KIND
// 2. NO METRICS OF ANY KIND
// 3. IF YOU WANT METRICS, INCLUDE A TRACKING CODE IN YOUR LINKED IMAGE AND TRACK INCOMING FROM CAMPAIGN
// 4. NO DISTASTEFUL OR DISRESPECTFUL LANGUAGE PERMITTED
// 5. MUST COMPLY WITH GITHUB TERMS OF SERVICE
// 6. MUST COMPLY WITH PROJECT APARIO TERMS OF SERVICE
// 7. MUST ACKNOWLEDGE THAT SUBMISSION OF ADVERTISING ITEM WILL BE "BAKED" INTO THE HISTORY OF THE PROJECT FOREVER
// 8. MUST ACKNOWLEDGE THAT SUBMISSION OF ADVERTISING ITEM WILL BE PUBLISHED UNDER THE MIT LICENSE
// 9. MUST ACKNOWLEDGE THAT YOU HAVE READ THESE TERMS AND AGREE TO COMPLY WITH ALL OF THE OUTLINED STATEMENTS

// IMPORTANT NOTES:
// 1. SOME CURRENCIES OFFER BETTER PRICING FOR COMPARABLE SERVICE.
// 2. IF PROJECT APARIO PAYS THE TRANSACTION FEE, THEN WE WILL REMOVE 3 DAYS FROM YOUR CAMPAIGN.
// 3. IF YOU PAY THE TRANSACTION FEE, AND THE AMOUNT IS > REQUIRED, WE WILL ADD 9 DAYS TO YOUR CAMPAIGN.
// -> -> THIS MEANS, IF THE BALANCE DUE IS 5 XMR AND WE RECEIVE 5.001 XMR (YOU PAY XMR FEE) THEN
// -> -> YOUR 240 CHARACTER CAMPAIGN WILL BE VALID FOR 99 DAYS TOTAL
// 4. YOUR CONTRIBUTION WILL BE PUBLIC DOMAIN KNOWLEDGE WITHIN THE BLOCKCHAIN UTILIZED
// 5. WE ACCEPT A MAXIMUM OF 12 TEXT ADS PER README PAGE AND 3 IMAGE ADS PER README PAGE
// 6. PROJECT APARIO WILL INTEGRATE SPONSORED MESSAGES INTO THE README DOCUMENTATION
// 7. ALL ADVERTISEMENTS INCLUDING THEIR HISTORIES WILL BE MAINTAINED IN advertisers.txt WITHIN THIS REPO
// 8. YOUR SUPPORT ENABLES FUTURE GROWTH OF THIS PROJECT.
// 9. INSTEAD OF JUST SUPPORTING THE PROJECT, YOU'RE GETTING ADVERTISING VISIBILITY FOR YOUR PRODUCT/SERVICE WHILE HELPING!

const XMR = `42DFbWLGgf7TG6cg8zKtEGAP1SLE2zcAqebqWFXrLxL4JXDtjVc7C4uMrAkJdGaHG1d3sbGEvphwfUhYdFgsQ3ZvRpaMzAv`

// 1 XMR = 60 Characters for 30 days
// 3 XMR = 120 Characters for 30 days
// 5 XMR = 240 Characters for 90 days
// 10 XMR = Upload 400 pixels wide by 200 pixels tall JPEG/GIF for 30 days in README.md
// 15 XMR = 10 XMR + 240 Characters for 30 days
// 17 XMR = 15 XMR for 66 days
// 20 XMR = 15 XMR for 120 days

const SOL = `5BA8HV6E4oBySt5jGmnikp1epr6CHAP7kUonoCWDwX7n`

// 1 SOL = 50 Characters for 30 days
// 3 SOL = 90 Characters for 30 days
// 5 SOL = 120 Characters for 30 days
// 10 SOL = 240 Characters for 60 days
// 15 SOL = 240 Characters for 90 days
// 17 SOL = Upload 400 pixels wide by 200 pixels tall JPEG/GIF for 30 days in README.md
// 27 SOL = 17 SOL + 90 Characters for 30 days
// 30 SOL = 17 SOL + 240 Characters for 30 days
// 33 SOL = 17 SOL + 90 Characters for 60 days
// 36 SOL = 17 SOL + 240 Characters for 60 days
// 45 SOL = 17 SOL + 240 Characters for 90 days
// 55 SOL = 17 SOL + 240 Characters for 120 days

const BTC = `1JwFosHJ9ysPA9UTvUoa8gL4w115wFHsTS`

// 0.001 BTC = 90 Characters for 30 days
// 0.002 BTC = 120 Characters for 30 days
// 0.007 BTC = 120 Characters for 90 days
// 0.012 BTC = 240 Characters for 60 days
// 0.017 BTC = 240 Characters for 90 days
// 0.021 BTC = 240 Characters for 120 days
// 0.027 BTC = Upload 400 pixels wide by 200 pixels tall JPEG/GIF for 30 days in README.md
// 0.030 BTC = 0.027 BTC + 120 Characters for 30 days
// 0.033 BTC = 0.027 BTC + 240 Characters for 30 days
// 0.036 BTC = 0.027 BTC + 120 Characters for 90 days
// 0.039 BTC = 0.027 BTC + 240 Characters for 90 days
// 0.045 BTC = 0.027 BTC + 240 Characters for 120 days

const ATOM = `cosmos1sxhag8dp0kwx54jzhy6qnyt3tef00y9k9qnre2`

// 3 ATOM = 30 Characters for 30 Days
// 4 ATOM = 40 Characters for 33 Days
// 5 ATOM = 50 Characters for 36 days
// 6 ATOM = 60 Characters for 39 Days
// 7 ATOM = 70 Characters for 42 days
// 8 ATOM = 80 Characters for 45 days
// 9 ATOM = 90 Characters for 48 days
// 10 ATOM = 100 Characters for 51 days
// 11 ATOM = 110 Characters for 54 days
// 12 ATOM = 120 Characters for 57 days
// 30 ATOM = Upload 400 pixels wide by 200 pixels tall JPEG/GIF for 30 days in README.md
// 60 ATOM = 30 ATOM + 30 days = 60 days
// 90 ATOM = 30 ATOM + 90 days = 120 days
// 120 ATOM = 30 ATOM + 120 days = 150 days

const RVN = `RMjBWExzb9YDkFSSExeYyPohmfcN8VoyJd`

// 2000 RVN = 20 Characters for 20 Days
// 3000 RVN = 30 Characters for 22 Days
// 4000 RVN = 40 Characters for 24 Days
// 5000 RVN = 50 Characters for 26 Days
// 6000 RVN = 60 Characters for 28 Days
// 7000 RVN = 70 Characters for 30 Days
// 14000 RVN = 120 Characters for 60 Days
// 20000 RVN = 240 Characters for 60 Days
// 25000 RVN = 120 Characters for 120 Days
// 30000 RVN = 240 Characters for 120 Days
// 60000 RVN = Upload 400 pixels wide by 200 pixels tall JPEG/GIF for 30 days in README.md
// 120000 RVN = 60000 RVN + 60 days
// 150000 RVN = 60000 RVN + 90 days
// 200000 RVN = 60000 RVN + 120 days
